# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inerview',
            name='datemixin_ptr',
        ),
        migrations.RemoveField(
            model_name='inerview',
            name='interviewer',
        ),
        migrations.RemoveField(
            model_name='inerview',
            name='publisher_linked',
        ),
        migrations.DeleteModel(
            name='DateMixin',
        ),
        migrations.DeleteModel(
            name='Inerview',
        ),
    ]
