# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 12:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interviews', '0002_auto_20160106_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inerview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_is_draft', models.BooleanField(db_index=True, default=True, editable=False)),
                ('publisher_modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('publisher_published_at', models.DateTimeField(editable=False, null=True)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
                ('date_modified', models.DateTimeField(default=datetime.datetime.now)),
                ('slug', models.SlugField()),
                ('video', embed_video.fields.EmbedVideoField()),
                ('title', models.CharField(max_length=500)),
                ('interviewee', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('publisher_linked', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher_draft', to='interviews.Inerview')),
            ],
            options={
                'abstract': False,
                'permissions': (('can_publish', 'Can publish'),),
            },
        ),
    ]
